#!/usr/bin/python3

def open_box(boxes, keys=[], visted_boxes = []):
    for i in keys:
        if i not in visted_boxes:
            visted_boxes.append(i)
            open_box(boxes, boxes[i], visted_boxes)
    if (len(boxes) - 1) == len(visted_boxes):
        return True
    return False

def canUnlockAll(boxes):
    """check for if the boxes contain keys for all other boxes or not"""
    start_box = boxes[0]
    visted_boxes = []
    result = open_box(boxes, start_box, visted_boxes)

    return result
	
	

boxes = [[1], [2], [3], [4], []]
print(canUnlockAll(boxes))

boxes = [[1, 4, 6], [2], [0, 4, 1], [5, 6, 2], [3], [4, 1], [6]]
print(canUnlockAll(boxes))

boxes = [[1, 4], [2], [0, 4, 1], [3], [], [4, 1], [5, 6]]
print(canUnlockAll(boxes))
